# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'root_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView


class Ui_rootinterface(object):
    def setupUi(self, rootinterface):
        rootinterface.setObjectName("rootinterface")
        rootinterface.resize(782, 691)
        self.list_shoplist = QtWidgets.QTableView(rootinterface)
        self.list_shoplist.setGeometry(QtCore.QRect(450, 190, 301, 451))
        self.list_shoplist.setObjectName("list_shoplist")
        #self.list_shopList.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        #self.list_shopList.verticalHeader().setVisible(False)
        self.label = QtWidgets.QLabel(rootinterface)
        self.label.setGeometry(QtCore.QRect(40, 20, 711, 151))
        self.label.setStyleSheet("font: 60pt \"Broadway\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(rootinterface)
        self.label_2.setGeometry(QtCore.QRect(60, 160, 101, 71))
        self.label_2.setStyleSheet("font: 40pt \"黑体\";")
        self.label_2.setObjectName("label_2")
        self.input_name = QtWidgets.QLineEdit(rootinterface)
        self.input_name.setGeometry(QtCore.QRect(110, 270, 291, 21))
        self.input_name.setObjectName("input_name")
        self.input_nums = QtWidgets.QLineEdit(rootinterface)
        self.input_nums.setGeometry(QtCore.QRect(110, 340, 291, 21))
        self.input_nums.setObjectName("input_nums")
        self.input_price = QtWidgets.QLineEdit(rootinterface)
        self.input_price.setGeometry(QtCore.QRect(110, 410, 291, 21))
        self.input_price.setObjectName("input_price")
        self.label_3 = QtWidgets.QLabel(rootinterface)
        self.label_3.setGeometry(QtCore.QRect(20, 400, 81, 31))
        self.label_3.setStyleSheet("font: 20pt \"黑体\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(rootinterface)
        self.label_4.setGeometry(QtCore.QRect(40, 320, 61, 51))
        self.label_4.setStyleSheet("font: 20pt \"黑体\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(rootinterface)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 61, 51))
        self.label_5.setStyleSheet("font: 20pt \"黑体\";")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(rootinterface)
        QtCore.QMetaObject.connectSlotsByName(rootinterface)

    def retranslateUi(self, rootinterface):
        _translate = QtCore.QCoreApplication.translate
        rootinterface.setWindowTitle(_translate("rootinterface", "Form"))
        self.label.setText(_translate("rootinterface", "MANAGER SYSTEM"))
        self.label_2.setText(_translate("rootinterface", "SET"))
        self.label_3.setText(_translate("rootinterface", "price"))
        self.label_4.setText(_translate("rootinterface", "nums"))
        self.label_5.setText(_translate("rootinterface", "name"))
