# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QHeaderView


class Ui_userInterface(object):
    def setupUi(self, userInterface):
        userInterface.setObjectName("userInterface")
        userInterface.resize(1065, 887)
        userInterface.setStyleSheet("font: 26pt \"Adobe Devanagari\";")
        self.centralwidget = QtWidgets.QWidget(userInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.output_buylist = QtWidgets.QLabel(self.centralwidget)
        self.output_buylist.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 8, 41);")
        self.output_buylist.setText("")
        self.output_buylist.setObjectName("output_buylist")
        self.gridLayout.addWidget(self.output_buylist, 4, 0, 1, 2)
        self.input_name = QtWidgets.QLineEdit(self.centralwidget)
        self.input_name.setObjectName("input_name")
        self.gridLayout.addWidget(self.input_name, 1, 1, 1, 1)
        self.button_buy = QtWidgets.QPushButton(self.centralwidget)
        self.button_buy.setStyleSheet("font: 12pt \"Adobe Devanagari\";")
        self.button_buy.setObjectName("button_buy")
        self.gridLayout.addWidget(self.button_buy, 3, 2, 1, 1)
        self.input_nums = QtWidgets.QLineEdit(self.centralwidget)
        self.input_nums.setObjectName("input_nums")
        self.gridLayout.addWidget(self.input_nums, 2, 1, 1, 1)
        self.list_shoplist = QtWidgets.QTableView(self.centralwidget)
        self.list_shoplist.setObjectName("list_shoplist")

        self.list_shoplist.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.list_shoplist.verticalHeader().setVisible(False)

        self.gridLayout.addWidget(self.list_shoplist, 1, 3, 4, 1)
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 1, 0, 1, 1)
        self.label_nums = QtWidgets.QLabel(self.centralwidget)
        self.label_nums.setObjectName("label_nums")
        self.gridLayout.addWidget(self.label_nums, 2, 0, 1, 1)
        self.shop_name = QtWidgets.QLabel(self.centralwidget)
        self.shop_name.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 50pt \"Blackadder ITC\";\n"
"")
        self.shop_name.setTextFormat(QtCore.Qt.AutoText)
        self.shop_name.setScaledContents(False)
        self.shop_name.setObjectName("shop_name")
        self.gridLayout.addWidget(self.shop_name, 0, 0, 1, 4)
        userInterface.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(userInterface)
        self.statusbar.setObjectName("statusbar")
        userInterface.setStatusBar(self.statusbar)

        self.retranslateUi(userInterface)
        QtCore.QMetaObject.connectSlotsByName(userInterface)

    def retranslateUi(self, userInterface):
        _translate = QtCore.QCoreApplication.translate
        userInterface.setWindowTitle(_translate("userInterface", "MainWindow"))
        self.button_buy.setText(_translate("userInterface", "购买"))
        self.label_name.setText(_translate("userInterface", "名称"))
        self.label_nums.setText(_translate("userInterface", "数量"))
        self.shop_name.setText(_translate("userInterface", "Sad Christmas flower shop"))
